### ISSUE TITLE
Add pagination mechanism

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/ars-arsenal#11]

**Comment by dce** [comment]
@nhunzaker is there any update on this? I think you mentioned this recently and it's now come up for WSB.

**Comment by nhunzaker** [comment]
Just following up. We have time to work on this. I could begin on this as early as tomorrow.

**Comment by cwmanning** [comment]
I was about to comment on the recent PR for 3.0.0, but thought it made more sense here. Should we update the examples to include pagination? Re-record the GIF demo used on the README? I might have some time to help later this week.

**Comment by nhunzaker** [comment]
We did it!
