### ISSUE TITLE
ES6 documentation

### ISSUE THREAD

**Issue by mzlock** [vigetlabs/ars-arsenal#20]
Documentation should mention use and dependency on ES6 and provide suggestions on including it in the Rails compile process.

Without ES6/Babel being properly configured, Rails gives the error:
```*** [err :: 52.20.246.178] ExecJS::ProgramError: Unexpected token punc «(», expected punc «:» (line: 21091, col: 10, pos: 614468)```

(when trying to precompile assets with rake)

**Comment by nhunzaker** [comment]
Ars should not depend on ES6. We actually compile it away before distributing it. If this is the case, then there is an issue in our build process before deploying to NPM.

**Comment by mzlock** [comment]
@nhunzaker - sorry, to be clear, your usage docs have an example set up in ES6.

**Comment by nhunzaker** [comment]
Ah okay. Done and done.

**Comment by mzlock** [comment]
Looks good :+1:
