### ISSUE TITLE
invalid .css file in build

### ISSUE THREAD

**Issue by mikestaub** [vigetlabs/ars-arsenal#76]
I cannot import the .css file because the last line is not valid css.

**Comment by nhunzaker** [comment]
Hey!

I'm actually working on a project using it right now and can import the CSS file.

What error are you experiencing?

**Comment by mikestaub** [comment]
If you run npm install ars-arsenal, then open this file:

`node_modules/ars-arsenal/style.css`

these are the first 3 lines:

```
yarn run v1.15.2
$ /home/nate/Work/ars-arsenal/node_modules/.bin/node-sass ./dist/style/ars-arsenal.scss --stdout
.ars-paper {
```

**Comment by nhunzaker** [comment]
Ah man. I totally see this now... Great...

I'll have a fix out shortly.

**Comment by nhunzaker** [comment]
Deployed as `ars-arsenal@3.5.1`. Give it a shot!

**Comment by mikestaub** [comment]
Fixed, thanks!
