### ISSUE TITLE
Help in integrating the library. Documentation is not self explanatory.

### ISSUE THREAD

**Issue by bharadwaj** [vigetlabs/ars-arsenal#93]
Hi there,

I am new to React area and its been challenging for me to integrate the library into my existing app. I tried following the documentation and was partially successful. I am able to see the Pick a Photo button without any errors, but when I click it I get error as shown in the image:  
`<title>Error</title> </head> <body> <pre>Cannot GET this error.`

 I believe my problem is in not properly constructing the request parameter in options because every time the request parameter is making a callback with empty q? parameter and getting a 404 error.

Any pointers to how I can fix this problem or any Codepen would be much helpful. 

Thank you.
![error](https://user-images.githubusercontent.com/107363/78089332-bf73da80-73e4-11ea-9134-d772ff54597d.png)

**Comment by cwmanning** [comment]
@bharadwaj it looks like there is no endpoint matching up with your configuration for ars-arsenal. Have you already set up a server-side component that returns a list of photos in JSON format? Based on this screenshot, that endpoint should be made available on http://localhost:3000.
